In [1]:
import numpy as np

In [2]:
x=np.array([65,63,67,64,68,62,70,66])

In [3]:
x

array([65, 63, 67, 64, 68, 62, 70, 66])

In [4]:
y=np.array([68,66,68,65,69,66,68,65])

In [5]:
y

array([68, 66, 68, 65, 69, 66, 68, 65])

In [6]:
r=np.corrcoef(x,y)

In [7]:
r

array([[1.        , 0.64199691],
       [0.64199691, 1.        ]])